print("WHAT IS YOUR NAME?")
user_name = input()
print(f'HELLO, {user_name}')
print("HOW OLD ARE YOU?")
user_age = input()
print(f'YOUR AGE IS {user_age}')
print("WHERE DO YOU LIVE?")
user_location = input()
print(f'YOU LIVE IN {user_location}')