a = float(input("Write first number (a):"))
b = float(input("write second number (b)"))

print("a+b", a+b)
print("a-b", a-b)
print("a*b", a*b)
print("a/b", a/b)
print("a**b", a**b)
print("a//b", a//b)
print("a%b", a%b)