#   Less 1_2
a = float(input("Enter digit a: "))
b = float(input("Enter digit b: "))
print("A + B =", a + b)
print("A - B =", a - b)
print("A * B =", a * b)
print("A / B =", a / b)
print("A ** B =", a ** b)
print("A // B =", a // b)
print("A % B =", a % b)