a = int(input("Hi, please entera number a:"))
b = int(input("Hi, please entera number b:"))

print("a+b =", a+b)
print("a-b =", a-b)
print("a/b =", a/b)
print("a*b =", a*b)
print("a**b =", a**b)
print("a//b =", a//b)
print("a%b =", a%b)