print("Hello!")
name = input("What's your name?\n")
age = input("How old are you?\n")
city = input("Where do you live?\n")
print()
print("Hello,", name)
print("Your age is -", age)
print("You live in", city)