a = float(input("Enter firs number\n"))
b = float(input("Enter second number\n"))
print()
print("A +B =",a + b)
print("A - B =",  a - b)
print("A * B =", a * b)
print("A / B =", a / b)
print("A ** B =", a ** b)
print("A // B =", a //b)
print("A % B =", a % b)